/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database_subscriptions;

import database_subscriptions.Customer_Page;
import database_subscriptions.Magazine_Subscription_Page;
import java.sql.*;

/**
 *
 * @author Em-kun
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Customers_Page = new javax.swing.JButton();
        Publication_Page = new javax.swing.JButton();
        Magazine_Subscription_Page = new javax.swing.JButton();
        Newspaper_Subscription_Page = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Customers_Page.setText("Customers Info");
        Customers_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customers_PageActionPerformed(evt);
            }
        });

        Publication_Page.setText("Publication Info");
        Publication_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Publication_PageActionPerformed(evt);
            }
        });

        Magazine_Subscription_Page.setText("Magazine Subcription Info");
        Magazine_Subscription_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Magazine_Subscription_PageActionPerformed(evt);
            }
        });

        Newspaper_Subscription_Page.setText("Newspaper Subscription Info");
        Newspaper_Subscription_Page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Newspaper_Subscription_PageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("SUBSCRIPTIONS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Authors: de Lemmus, Emerson & McAntosh Brendan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Customers_Page)
                .addGap(309, 309, 309)
                .addComponent(Publication_Page)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Magazine_Subscription_Page)
                .addGap(145, 145, 145)
                .addComponent(Newspaper_Subscription_Page)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(400, 400, 400))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customers_Page)
                    .addComponent(Publication_Page)
                    .addComponent(Magazine_Subscription_Page)
                    .addComponent(Newspaper_Subscription_Page))
                .addGap(388, 388, 388))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Customers_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customers_PageActionPerformed
        // TODO add your handling code here:
        Customer_Page customer_Page = new Customer_Page();
        customer_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Customers_PageActionPerformed

    private void Publication_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Publication_PageActionPerformed
        // TODO add your handling code here:
        Publication_Page publication_Page = new Publication_Page();
        publication_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Publication_PageActionPerformed

    private void Magazine_Subscription_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Magazine_Subscription_PageActionPerformed
        // TODO add your handling code here:
        Magazine_Subscription_Page Magazine_subscription_Page = new Magazine_Subscription_Page();
        Magazine_subscription_Page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Magazine_Subscription_PageActionPerformed

    private void Newspaper_Subscription_PageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Newspaper_Subscription_PageActionPerformed
        // TODO add your handling code here:
        Newspaper_Subscription_Page NewspaperSubpage = new Newspaper_Subscription_Page();
        NewspaperSubpage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Newspaper_Subscription_PageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        Connection conn = null;
        
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/databaseschema_5318", "root", "1234");
            if (conn != null)
            {
                System.out.println("Connected to Database Successfully");
            }
        }catch(Exception e)
        {
            System.out.println("not connected to database.");
           
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customers_Page;
    private javax.swing.JButton Magazine_Subscription_Page;
    private javax.swing.JButton Newspaper_Subscription_Page;
    private javax.swing.JButton Publication_Page;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
